###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3"
services:

  admin-traefik:
    image: "traefik:v2.2"
    restart: always
    container_name: "admin-traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8888:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  admin-mail:
    image: mailhog/mailhog:latest
    container_name: admin-mail
    ports:
      - "8862:8025"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailhog-tls.rule=Host(`admin-mail.localhost`)"
      - "traefik.http.routers.mailhog-tls.service=mailhog"
      - "traefik.http.routers.mailhog-tls.entrypoints=websecure"
      - "traefik.http.routers.mailhog-tls.tls=true"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"

  admin-db:
    image: postgres:11.1-alpine
    container_name: admin-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5436:5432"

  admin-web:
    image: nginx:alpine
    container_name: admin-web
    working_dir: /application
    volumes:
      - ${PATH_DEMO_CODE}:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin-tls.rule=Host(`admin-web.localhost`)"
      - "traefik.http.routers.admin-tls.entrypoints=websecure"
      - "traefik.http.routers.admin-tls.tls=true"

  admin:
    build: ./docker/php-fpm
    container_name: admin
    working_dir: /application
    volumes:
      - ${PATH_DEMO_CODE}:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

