###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3"
services:

    admin-mailhog:
      image: mailhog/mailhog:latest
      container_name: admin-mail
      ports:
        - "8862:8025"

    admin-db:
      image: postgres:11.1-alpine
      container_name: admin-db
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=backendpos
      ports:
        - "5436:5432"

    admin-web:
      image: nginx:alpine
      container_name: admin-web
      working_dir: /application
      volumes:
          - ./admin-demo:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8861:80"

    admin:
      build: ./docker/php-fpm
      container_name: admin
      working_dir: /application
      volumes:
        - ./admin-demo:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

